### PR TITLE
feat: add bbox thickness option

### PR DESCRIPTION
**Pull request by oatiz**

### CODE REVIEW

**Comment by jamjamjon** [comment]
This implementation may have a potential issue: when the line width is greater than the shorter side of the bounding box.This can occur when the target is very small, and the user has entered a larger value.

We should consider this situation. An upper limit should be set to ensure the visibility of the target; for example, this value should be one-third of the shorter side. 

Additionally, a new method of displaying the bounding box could be introduced, such as an overlay on top of the bounding box. 

Nonetheless, increasing the line width always provides users with a better option!

**Comment by oatiz** [comment]
@jamjamjon Please review

**Comment by jamjamjon** [comment]
Thank you very much for your code modifications. I have two questions:

1. Apart from `ThicknessSide::All`, what is the purpose of the other values in the `ThicknessSide` enum? In which scenarios would they be used? Do we really need this enum?
2. I noticed that when simulating an increase in line width, the lines move outward. This creates another boundary issue: the coordinates do not align with the label box (as shown in the image below). This means that the coordinates of the label box also need to be adjusted.

Please share your thoughts with me.

image

**Comment by oatiz** [comment]
Initially, this option was considered because, in certain scenarios, the line width of the bounding box was too small, making it difficult for me to locate the target. Therefore, I wanted to increase the thickness to facilitate finding the target.

1. the `ThicknessSide` enum does indeed seem unnecessary.  :rofl:
2. Excessive thickness parameters can be somewhat unreasonable. Generally, a thickness parameter of around 4 is sufficient to clearly identify the bounding box.

I believe we should follow your initial idea and display the bounding box in two ways:
1. Similar to the polygon method, by adding an overlay.
2. By increasing the thickness of the bounding box. (Default thickness should be specified based on the image size, referencing [`supervision`](https://github.com/roboflow/supervision/blob/6de21048d2569641be880b58c73aba91cc16a9b8/supervision/draw/utils.py#L307))

**Comment by jamjamjon** [comment]
I made some simple adjustments to the code:

1. Removed the `ThicknessSide` enum and replaced it solely with the previous approach using `ThicknessSide::All`.
2. Adjusted the position of the text box to accommodate changes in the bbox line width

Here is the current result:


If you have time in the future to implement a feature similar to what [supervision](https://github.com/roboflow/supervision.git) provides, it will definitely be cool! @oatiz

**Pull request merged**
